### ISSUE TITLE
Unify $extends syntax

### ISSUE THREAD

**Issue by razetdinov** [yandex-ui/yandex-domain-configs#4]
Проблема 1: `$extends` ведёт себя по разному в корне (наследует файл) и в домене (наследует домен).

Проблема 2: допустим, мы показываем рекламу только на части доменов, а код csp-правил для рекламы лежит в отдельном файле (и даже в отдельном пакете). Сейчас невозможно подключить сторонний файл в настройки домена.

Предложение: унифицировать `$extends` и привести к формату `$ref` в JSON Schema:

```
$extends: foo.yaml
$domains:
  example.com:
  example-with-ads.com:
    $extends:
      - '#/$domains/example.com'
      - csp-for-ads.yaml
```
